//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralParking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    public partial class Locador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locador()
        {
            this.Vagas = new HashSet<Vagas>();
        }
    
        public int ID_Dono { get; set; }

        [Required(ErrorMessage="Digite seu nome completo")]
        [Display (Name ="Nome Completo")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,100}$",ErrorMessage ="Não utilizar caracteres especiais")]
        public string Nome_Dono { get; set; }

        [Required(ErrorMessage ="Digite seu CPF")]
        [CustomValidationCPF(ErrorMessage ="CPF Inválido")]
        public decimal CPF { get; set; }

        [Required(ErrorMessage ="Digite seu email")]
        [Display(Name ="Email")]
        [RegularExpression(".+\\@.+\\..+",ErrorMessage ="Informe um email válido")]
        [StringLength(150, MinimumLength = 12,ErrorMessage ="Informe um email válido")]
        public string email { get; set; }

        [Display(Name ="Usuário")]
        [Required(ErrorMessage ="Digite um nome de usuário")]
        [StringLength(100, MinimumLength = 8, ErrorMessage = "Valor minímo de 8 caracteres")]
        public string usuario { get; set; }
        
        [Display(Name ="Senha")]
        [Required(ErrorMessage ="Digite uma senha")]
        [DataType(DataType.Password)]
        
        public string senha { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vagas> Vagas { get; set; }
    }
}
